version: "3.7"

volumes:
  files:

services:
  lufi:
    build:
     context: .
     args:
        UID: ${HOST_UID:-1000}
        GID: ${HOST_GID:-1000}
    container_name: lufi-app
    ports:
      - "8081:8081"
    restart: unless-stopped
    volumes:
      - files:/home/nonroot/lufi/files
